(function () {
  const MAP = {
"1WA": {mainLocation: "1W", department: "Pyxis", group: "2", amshift: "AM2", pmshift: "PM2", eveningshift: "EV1" },
"1WB": {mainLocation: "1W", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"2EA": {mainLocation: "2E", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"2EBC": {mainLocation: "2E", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"2WA": {mainLocation: "2W", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"2WB": {mainLocation: "2W", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"3TWA": {mainLocation: "3TW", department: "Pyxis", group: "3", amshift: "", pmshift: "", eveningshift: "" },
"3TWB": {mainLocation: "3TW", department: "Pyxis", group: "3", amshift: "", pmshift: "", eveningshift: "" },
"3TWC": {mainLocation: "3TW", department: "Pyxis", group: "3", amshift: "", pmshift: "", eveningshift: "" },
"AA": {mainLocation: "ASC", department: "Pyxis", group: "4", amshift: "", pmshift: "", eveningshift: "" },
"AB": {mainLocation: "ASC", department: "Pyxis", group: "4", amshift: "", pmshift: "", eveningshift: "" },
"AC": {mainLocation: "ASC", department: "Pyxis", group: "4", amshift: "", pmshift: "", eveningshift: "" },
"AD": {mainLocation: "ASC", department: "Pyxis", group: "4", amshift: "", pmshift: "", eveningshift: "" },
"AE": {mainLocation: "ASC", department: "Pyxis", group: "4", amshift: "", pmshift: "", eveningshift: "" },
"ASC": {mainLocation: "ASC", department: "Pyxis", group: "4", amshift: "", pmshift: "", eveningshift: "" },
"ASCOR": {mainLocation: "ASC", department: "Pyxis", group: "4", amshift: "", pmshift: "", eveningshift: "" },
"Chemo IV Room Fridge": {mainLocation: "IV Chemo", department: "Pharmacy", group: "6", amshift: "", pmshift: "", eveningshift: "" },
"Chemo IV Room Shelf": {mainLocation: "IV Chemo", department: "Pharmacy", group: "6", amshift: "", pmshift: "", eveningshift: "" },
"CL2": {mainLocation: "CL", department: "Pyxis", group: "5", amshift: "", pmshift: "", eveningshift: "" },
"CL3": {mainLocation: "CL", department: "Pyxis", group: "5", amshift: "", pmshift: "", eveningshift: "" },
"CL4": {mainLocation: "CL", department: "Pyxis", group: "5", amshift: "", pmshift: "", eveningshift: "" },
"CLA": {mainLocation: "CL", department: "Pyxis", group: "5", amshift: "", pmshift: "", eveningshift: "" },
"CLA1": {mainLocation: "CL", department: "Pyxis", group: "5", amshift: "", pmshift: "", eveningshift: "" },
"CLA2": {mainLocation: "CL", department: "Pyxis", group: "5", amshift: "", pmshift: "", eveningshift: "" },
"CLA4": {mainLocation: "CL", department: "Pyxis", group: "5", amshift: "", pmshift: "", eveningshift: "" },
"CLCT": {mainLocation: "CL", department: "Pyxis", group: "5", amshift: "", pmshift: "", eveningshift: "" },
"CLSPA": {mainLocation: "CL", department: "Pyxis", group: "5", amshift: "", pmshift: "", eveningshift: "" },
"CRASH CARTS": {mainLocation: "Crash Cart", department: "Pharmacy", group: "6", amshift: "", pmshift: "", eveningshift: "" },
"EDA": {mainLocation: "ED", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"EDB": {mainLocation: "ED", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"EDC": {mainLocation: "ED", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"EDD": {mainLocation: "ED", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"EDLOBY": {mainLocation: "ED", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"EDR": {mainLocation: "ED", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"EDTRAM": {mainLocation: "ED", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"ENA": {mainLocation: "ANES", department: "Pyxis", group: "8", amshift: "", pmshift: "", eveningshift: "" },
"ENA2": {mainLocation: "ANES", department: "Pyxis", group: "8", amshift: "", pmshift: "", eveningshift: "" },
"ENDO": {mainLocation: "ENDO", department: "Pyxis", group: "8", amshift: "", pmshift: "", eveningshift: "" },
"Freezer R1": {mainLocation: "Freezer", department: "Pharmacy", group: "6", amshift: "", pmshift: "", eveningshift: "" },
"Frig R105": {mainLocation: "Fridge", department: "Pharmacy", group: "6", amshift: "", pmshift: "", eveningshift: "" },
"Frig R107": {mainLocation: "Fridge", department: "Pharmacy", group: "6", amshift: "", pmshift: "", eveningshift: "" },
"Frig R11": {mainLocation: "Fridge", department: "Pharmacy", group: "6", amshift: "", pmshift: "", eveningshift: "" },
"Frig R135": {mainLocation: "Fridge", department: "Pharmacy", group: "6", amshift: "", pmshift: "", eveningshift: "" },
"ICUB": {mainLocation: "ICU", department: "Pyxis", group: "3", amshift: "7", pmshift: "", eveningshift: "" },
"ICUC": {mainLocation: "ICU", department: "Pyxis", group: "3", amshift: "7", pmshift: "", eveningshift: "" },
"ICUD": {mainLocation: "ICU", department: "Pyxis", group: "3", amshift: "7", pmshift: "", eveningshift: "" },
"ICUE": {mainLocation: "ICU", department: "Pyxis", group: "3", amshift: "7", pmshift: "", eveningshift: "" },
"IR2": {mainLocation: "IR", department: "Pyxis", group: "3", amshift: "5", pmshift: "", eveningshift: "" },
"IR3": {mainLocation: "IR", department: "Pyxis", group: "3", amshift: "5", pmshift: "", eveningshift: "" },
"LDPAB": {mainLocation: "LD", department: "Pyxis", group: "4", amshift: "9", pmshift: "", eveningshift: "" },
"LDPACU": {mainLocation: "LD", department: "Pyxis", group: "4", amshift: "9", pmshift: "", eveningshift: "" },
"LDPDE": {mainLocation: "LD", department: "Pyxis", group: "4", amshift: "9", pmshift: "", eveningshift: "" },
"LOR1": {mainLocation: "LD", department: "Pyxis", group: "4", amshift: "9", pmshift: "", eveningshift: "" },
"LOR2": {mainLocation: "LD", department: "Pyxis", group: "4", amshift: "9", pmshift: "", eveningshift: "" },
"LYMPH": {mainLocation: "MOB8", department: "Outpatient", group: "9", amshift: "", pmshift: "", eveningshift: "" },
"MEDAB": {mainLocation: "MED", department: "Pyxis", group: "1", amshift: "", pmshift: "", eveningshift: "" },
"MEDCD": {mainLocation: "MED", department: "Pyxis", group: "1", amshift: "", pmshift: "", eveningshift: "" },
"MSA": {mainLocation: "MS", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"MSB": {mainLocation: "MS", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"MSC": {mainLocation: "MS", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"NICU": {mainLocation: "NICU", department: "Pyxis", group: "1", amshift: "", pmshift: "", eveningshift: "" },
"NSY": {mainLocation: "NSY", department: "Pyxis", group: "1", amshift: "", pmshift: "", eveningshift: "" },
"NUC": {mainLocation: "NUC", department: "Pyxis", group: "5", amshift: "", pmshift: "", eveningshift: "" },
"ONCA": {mainLocation: "ONC", department: "Pyxis", group: "1", amshift: "", pmshift: "", eveningshift: "" },
"ONCB": {mainLocation: "ONC", department: "Pyxis", group: "1", amshift: "", pmshift: "", eveningshift: "" },
"ONCC": {mainLocation: "ONC", department: "Pyxis", group: "1", amshift: "", pmshift: "", eveningshift: "" },
"OR": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR1": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR10": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR11": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR12": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR14": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR15": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR2": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR3": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR4": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR5": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR6": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR7": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR8": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"OR9": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"PACU1": {mainLocation: "PACU", department: "Pyxis", group: "4", amshift: "", pmshift: "", eveningshift: "" },
"PACU2": {mainLocation: "PACU", department: "Pyxis", group: "4", amshift: "", pmshift: "", eveningshift: "" },
"PEDS": {mainLocation: "PED", department: "Pyxis", group: "1", amshift: "", pmshift: "", eveningshift: "" },
"PPC": {mainLocation: "PP", department: "Pyxis", group: "1", amshift: "", pmshift: "", eveningshift: "" },
"RESP": {mainLocation: "RESP", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"SPA": {mainLocation: "SPA", department: "Pyxis", group: "", amshift: "", pmshift: "", eveningshift: "" },
"SRIBC": {mainLocation: "SRI", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"SRID": {mainLocation: "SRI", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"STERIL": {mainLocation: "OR", department: "Pyxis", group: "7", amshift: "", pmshift: "", eveningshift: "" },
"SUR1": {mainLocation: "SUR", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"SUR2AB": {mainLocation: "SUR", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"SUR2CD": {mainLocation: "SUR", department: "Pyxis", group: "2", amshift: "", pmshift: "", eveningshift: "" },
"TELAB": {mainLocation: "TEL", department: "Pyxis", group: "1", amshift: "", pmshift: "", eveningshift: "" },
"TELCD": {mainLocation: "TEL", department: "Pyxis", group: "1", amshift: "", pmshift: "", eveningshift: "" },
"TNIA": {mainLocation: "TNI", department: "Pyxis", group: "3", amshift: "", pmshift: "", eveningshift: "" },
"TNIB": {mainLocation: "TNI", department: "Pyxis", group: "3", amshift: "", pmshift: "", eveningshift: "" },
"TNIC": {mainLocation: "TNI", department: "Pyxis", group: "3", amshift: "", pmshift: "", eveningshift: "" },
"TRACLN": {mainLocation: "ED", department: "Pyxis", group: "3", amshift: "", pmshift: "", eveningshift: "" },
"VC1": {mainLocation: "Carousel", department: "Pharmacy", group: "6", amshift: "", pmshift: "", eveningshift: "" },
"VC2": {mainLocation: "Carousel", department: "Pharmacy", group: "6", amshift: "", pmshift: "", eveningshift: "" }
  };
  const g = (typeof globalThis !== 'undefined') ? globalThis : (typeof window !== 'undefined' ? window : this);
  g.SUBLOCATION_MAP = g.SUBLOCATION_MAP || MAP;
  })();

// Expose to globalThis for loader/merger code that scans window/globalThis.
try { globalThis.MAP = MAP; } catch (e) { /* ignore */ }
